name: Vanilla Desktop Waydroid
id: waydroid
stages:
- id: build
  base: ghcr.io/vanilla-os/desktop:dev
  singlelayer: false
  labels:
    maintainer: Vanilla OS Contributors
  args:
    DEBIAN_FRONTEND: noninteractive
  runs:
    commands:
      - echo 'APT::Install-Recommends "1";' > /etc/apt/apt.conf.d/01norecommends

  modules:
  - name: init-setup
    type: shell
    commands:
    - lpkg --unlock
    - apt update

  - name: waydroid-repo
    type: shell
    commands:
      - curl --progress-bar --proto '=https' --tlsv1.2 -Sf https://repo.waydro.id/waydroid.gpg --output /usr/share/keyrings/waydroid.gpg
      - echo "deb [signed-by=/usr/share/keyrings/waydroid.gpg] https://repo.waydro.id/ sid main" | tee /etc/apt/sources.list.d/waydroid.list
      - apt update

  - name: waydroid
    type: apt
    source:
      packages:
      - waydroid

  - name: cleanup
    type: shell
    commands:
    - apt autoremove -y
    - apt clean
    - lpkg --lock

  - name: fsguard
    type: fsguard
    FsGuardLocation: "/usr/sbin/FsGuard"
    CustomFsGuard: false
    GenerateKey: true
    FilelistPaths: ["/usr/bin"]
    modules:
      - name: remove-prev-fsguard
        type: shell
        commands:
          - rm -rf /FsGuard
          - rm -f ./minisign.pub ./minisign.key
          - chmod +x /usr/sbin/init
